services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
    
  backend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: node ./server/server.js
    ports:
      - "3000:3000"
